apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
- source:
    fieldPath: spec.template.spec.containers.[name=manager].image
    kind: Deployment
    name: operator
  targets:
  - fieldPaths:
    - metadata.annotations.containerImage
    select:
      name: reference-addon.v0.0.0
patchesStrategicMerge:
  - ./cluster_service_version_patch.yaml
resources:
- ../../deploy
components:
- ../../components/olm
