apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reference-addon-operator
images:
- name: manager
  newName: quay.io/openshift/reference-addon-manager
  newTag: latest
resources:
- ./00_namespace.yaml
- ../../deploy
