apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: reference-addon-
commonLabels:
  app.kubernetes.io/name: reference-addon-operator
resources:
- deployment.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
