apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: reference-addon-ms
  namespace: redhat-reference-addon
  labels:
    app.kubernetes.io/name: reference-addon
spec:
  logLevel: debug
  retention: 1d
  resourceSelector:
    matchLabels:
      app.kubernetes.io/name: reference-addon
