apiVersion: v1
kind: ServiceAccount
metadata:
  name: reference-addon
  namespace: redhat-reference-addon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reference-addon
  namespace: redhat-reference-addon
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - reference.addons.managed.openshift.io
  resources:
  - referenceaddons
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkworking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reference-addon
  namespace: redhat-reference-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reference-addon
subjects:
- kind: ServiceAccount
  name: reference-addon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reference-addon
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reference-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reference-addon
subjects:
- kind: ServiceAccount
  name: reference-addon
  namespace: redhat-reference-addon
