apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reference-addon
  namespace: redhat-reference-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reference-addon
subjects:
- kind: ServiceAccount
  name: reference-addon
