apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-addon
  namespace: redhat-reference-addon
  labels:
    app.kubernetes.io/name: reference-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-addon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-addon
    spec:
      serviceAccountName: reference-addon
      containers:
      - name: manager
        image: quay.io/openshift/reference-addon:latest
        args:
        - --enable-leader-election
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
